# Generated by Django 4.2 on 2023-04-29 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catégorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ImageProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL_Image_Produit', models.CharField(max_length=250)),
                ('Nom_Image_Produit', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=50)),
                ('Pourcentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Date_Début', models.DateField()),
                ('Date_Fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=250)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('catégorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercadona_back.catégorie')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercadona_back.imageproduit')),
                ('promotion', models.ManyToManyField(to='mercadona_back.promotion')),
            ],
        ),
    ]
